config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "lists#index"
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @movies = Movie.all
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save!
      redirect_to lists_path
    else
      raise
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movies_id, :lists_id)
  end

  def destroy
    @bookmark = bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @list = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<% @movies.each do |movie| %>
<h1><%= movie.title %></h1>
<%= simple_form_for(@bookmark, url: list_bookmarks_path(@list)) do |f| %>
<%= f.input :comment %>
<%= f.hidden_field :movies_id, value: movie.id %>
<%= f.hidden_field :lists_id, value: @list.id %>
<%= f.submit %>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= "LISTS" %>
<div id="list">
  <% @list.each do |list| %>
    <%= list.name %>
    <p>
      <%= link_to "Open list", list %>
    </p>
  <% end %>
    <%= link_to "ADD NEW LIST", new_list_path  %>
</div>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
<%= f.input :name %>
<%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>
<br>
<%= link_to "back to lists", lists_path %>
<%= link_to "add a bookmark", new_list_bookmark_path(@list) %>
<%# <%= link_to "add a bookmark", new_list_bookmark_path%>